################################################################################
#
# mediastreamer4
#
################################################################################

MEDIASTREAMER4_VERSION = 4.4.8
MEDIASTREAMER4_SOURCE = mediastreamer4-$(MEDIASTREAMER4_VERSION).tar.gz
MEDIASTREAMER4_SITE = $(TOPDIR)/EmergUnit
MEDIASTREAMER4_SITE_METHOD = file
MEDIASTREAMER4_LICENSE = GPL-3.0+
MEDIASTREAMER4_LICENSE_FILES = LICENSE.txt
MEDIASTREAMER4_INSTALL_STAGING = YES
MEDIASTREAMER4_DEPENDENCIES = ortp4
MEDIASTREAMER4_CONF_OPTS = \
	-DENABLE_DOC=OFF \
	-DENABLE_GL=OFF \
	-DENABLE_GLX=OFF \
	-DENABLE_MKV=OFF \
	-DENABLE_SOUND=OFF \
	-DENABLE_STRICT=OFF \
	-DENABLE_TOOLS=OFF \
	-DENABLE_UNIT_TESTS=OFF \
	-DENABLE_ZRTP=OFF \
	-DENABLE_G726=ON

MEDIASTREAMER4_DEPENDENCIES += webrtc-audio-processing spandsp

ifeq ($(BR2_PACKAGE_ALSA_LIB_MIXER)$(BR2_PACKAGE_ALSA_LIB_PCM),yy)
MEDIASTREAMER4_CONF_OPTS += \
	-DENABLE_ALSA=ON \
	-DENABLE_SOUND=ON
MEDIASTREAMER4_DEPENDENCIES += alsa-lib
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_ALSA=OFF
endif

ifeq ($(BR2_PACKAGE_BCG729),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_G729=ON
MEDIASTREAMER4_DEPENDENCIES += bcg729
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_G729=OFF
endif

ifeq ($(BR2_PACKAGE_JPEG_TURBO),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_JPEG=ON
MEDIASTREAMER4_DEPENDENCIES += jpeg
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_JPEG=OFF
endif

ifeq ($(BR2_PACKAGE_LIBGSM),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_GSM=ON
MEDIASTREAMER4_DEPENDENCIES += libgsm
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_GSM=OFF
endif

ifeq ($(BR2_PACKAGE_LIBPCAP),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_PCAP=ON
MEDIASTREAMER4_DEPENDENCIES += libpcap
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_PCAP=OFF
endif

ifeq ($(BR2_PACKAGE_LIBSRTP),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SRTP=ON
MEDIASTREAMER4_DEPENDENCIES += libsrtp
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SRTP=OFF
endif

ifeq ($(BR2_PACKAGE_LIBVPX),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_VPX=ON
MEDIASTREAMER4_DEPENDENCIES += libvpx
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_VPX=OFF
endif

ifeq ($(BR2_PACKAGE_OPUS),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_OPUS=ON
MEDIASTREAMER4_DEPENDENCIES += opus
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_OPUS=OFF
endif

# portaudio backend needs speexdsp as well
ifeq ($(BR2_PACKAGE_PORTAUDIO)$(BR2_PACKAGE_SPEEXDSP),yy)
MEDIASTREAMER4_CONF_OPTS += \
	-DENABLE_PORTAUDIO=ON \
	-DENABLE_SOUND=ON
MEDIASTREAMER4_DEPENDENCIES += portaudio
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_PORTAUDIO=OFF
endif

ifeq ($(BR2_PACKAGE_PULSEAUDIO),y)
MEDIASTREAMER4_CONF_OPTS += \
	-DENABLE_PULSEAUDIO=ON \
	-DENABLE_SOUND=ON
MEDIASTREAMER4_DEPENDENCIES += pulseaudio
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_PULSEAUDIO=OFF
endif

ifeq ($(BR2_PACKAGE_SPEEX),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SPEEX_CODEC=ON
MEDIASTREAMER4_DEPENDENCIES += speex
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SPEEX_CODEC=OFF
endif

ifeq ($(BR2_PACKAGE_SPEEXDSP),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SPEEX_DSP=ON
MEDIASTREAMER4_DEPENDENCIES += speexdsp
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SPEEX_DSP=OFF
endif

ifeq ($(BR2_PACKAGE_SPEEX)$(BR2_PACKAGE_SPEEXDSP),yy)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_RESAMPLE=ON
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_RESAMPLE=OFF
endif

ifeq ($(BR2_PACKAGE_FFMPEG_SWSCALE),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_FFMPEG=ON
MEDIASTREAMER4_DEPENDENCIES += ffmpeg
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_FFMPEG=OFF
endif

ifeq ($(BR2_PACKAGE_SDL),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SDL=ON
MEDIASTREAMER4_DEPENDENCIES += sdl
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SDL=OFF
endif

ifeq ($(BR2_PACKAGE_XLIB_LIBX11),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_X11=ON
MEDIASTREAMER4_DEPENDENCIES += xlib_libX11
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_X11=OFF
endif

ifeq ($(BR2_PACKAGE_XLIB_LIBXV),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_XV=ON
MEDIASTREAMER4_DEPENDENCIES += xlib_libXv
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_XV=OFF
endif

ifeq ($(BR2_PACKAGE_LIBTHEORA),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_THEORA=ON
MEDIASTREAMER4_DEPENDENCIES += libtheora
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_THEORA=OFF
endif

ifeq ($(BR2_PACKAGE_LIBV4L),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_V4L=ON
MEDIASTREAMER4_DEPENDENCIES += libv4l
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_V4L=OFF
endif

ifeq ($(BR2_PACKAGE_ZXING_CPP),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_QRCODE=ON
MEDIASTREAMER4_DEPENDENCIES += zxing-cpp
else
MEDIASTREAMER4_CONF_OPTS += -DENABLE_QRCODE=OFF
endif

ifeq ($(BR2_STATIC_LIBS),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SHARED=OFF -DENABLE_STATIC=ON
else ifeq ($(BR2_SHARED_STATIC_LIBS),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SHARED=ON -DENABLE_STATIC=ON
else ifeq ($(BR2_SHARED_LIBS),y)
MEDIASTREAMER4_CONF_OPTS += -DENABLE_SHARED=ON -DENABLE_STATIC=OFF
endif

$(eval $(cmake-package))
