#!/bin/sh

[ -x /sbin/acpid ] || exit 0

case "$1" in
  start)
	/sbin/acpid
	;;
  stop)
	killall acpid
	;;
  restart|reload)
	$0" stop
	$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
