#!/bin/sh

[ -x /usr/bin/unicode_start ] || exit 0
[ -x /usr/bin/loadkeys ] || exit 0

export LANG=ru_RU.UTF-8

case "$1" in
  start)
	/usr/bin/unicode_start cyr-sun16
	/usr/bin/loadkeys ruwin_cplk-UTF-8
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
