#!/bin/sh

[ -x /root/affine.sh ] || exit 0
[ -x /usr/lib/qt/examples/widgets/painting/affine/affine ] || exit 0

case "$1" in
  start)
	/root/affine.sh &
	;;
  stop)
	killall affine
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
