#!/bin/sh

[ -f /root/a2002011001-e02-8kHz.wav ] || exit 0
[ -x /usr/bin/aplay ] || exit 0

case "$1" in
  start)
	/usr/bin/aplay /root/a2002011001-e02-8kHz.wav &
	;;
  stop)
	killall aplay
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
