#!/bin/sh

[ -x /usr/sbin/gpio-watch ] || exit 0

case "$1" in
  start)
	/usr/sbin/gpio-watch 52:falling &
	;;
  stop)
	killall gpio-watch
	;;
  restart|reload)
	$0" stop
	$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
